# Generated by Django 5.2.8 on 2025-11-21 10:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_email_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
