# Generated by Django 5.2.8 on 2025-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("Dept", models.CharField(max_length=50)),
            ],
        ),
    ]
