# Generated by Django 5.2.8 on 2025-11-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Dept",
            new_name="dept",
        ),
    ]
