# Generated by Django 5.2.8 on 2025-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0003_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("retirement", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "other_benefits",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_benefits",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_compensation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
    ]
