# Generated by Django 5.2.8 on 2025-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0004_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.IntegerField(default=0),
        ),
    ]
