# Generated by Django 5.2.8 on 2025-11-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stockdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "price_changed",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "percentage_changed",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "week_52_high",
                    models.FloatField(blank=True, max_length=20, null=True),
                ),
                (
                    "week_52_low",
                    models.FloatField(blank=True, max_length=20, null=True),
                ),
                (
                    "volume",
                    models.BigIntegerField(blank=True, max_length=20, null=True),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockanalysis.stock",
                    ),
                ),
            ],
        ),
    ]
