# Generated by Django 5.2.8 on 2025-11-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0002_stockdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="dividend_yield",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="market_cap",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pe_ratio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
