# Generated by Django 5.2.8 on 2025-11-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stockanalysis",
            "0003_stockdata_dividend_yield_stockdata_market_cap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="previous_close",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
