# Generated by Django 5.2.8 on 2025-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0004_stockdata_previous_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="volume",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="week_52_high",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="week_52_low",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
