# Generated by Django 5.2.8 on 2025-11-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "stockanalysis",
            "0005_alter_stockdata_volume_alter_stockdata_week_52_high_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockdata",
            name="price_changed",
        ),
    ]
