# Generated by Django 5.2.8 on 2025-11-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Uploadfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_file", models.FileField(upload_to="upload/")),
                ("model_name", models.CharField(max_length=100)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
